### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by fsandel** [fsandel/cub3D#7]
- [x] Clean up and create pull request from first 3d version
- [x] wall collision
- [x] check fov
- [x] check distance to line
- [x] color cubes different based on direction i am looking at
